#!/bin/bash
cd samples

for i in *.mila ; do
  j="${i%%.*}"
  echo "$("../cmake-build-debug/mila" $i)" > /dev/null
  clang++ "./output.o" -o "$j"
  echo "../cmake-build-debug/mila" "$i" -o "$j"
done
rm -f output.o